server:
  port: 8090

spring:
  application:
    name: ${APPLICATION_NAME}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    hikari:
      schema: ${database.schema.name}
      idle-timeout: 120000
      max-lifetime: 300000

  liquibase:
    enabled: true
    default-schema: ${database.schema.name}
    liquibase-schema: ${database.schema.name}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${database.schema.name}

database:
  schema:
    name: ${DATABASE_SCHEMA_NAME}

bot:
  username: ${BOT_USERNAME}
  token: ${BOT_TOKEN}

cache:
  users:
    max_size: 1000
    refresh_after_write_duration: 7200 # seconds
    expire_after_write_duration: 86400 # seconds

options:
  room:
    min_length_name: 4
    max_length_name: 30
    min_count_users: 3
    max_count_users: 20