package com.example.secretsantatelegrambot.entity.enums;

public enum UserState {
    START,
    AWAITING_CREATE_NAME_ROOM,
    AWAITING_CREATE_MIN_COUNT_USERS_ROOM,
    AWAITING_CREATE_MAX_COUNT_USERS_ROOM,
    AWAITING_CREATE_MIN_COST_GIFT_ROOM,
    AWAITING_UPDATE_NAME_ROOM,
    AWAITING_UPDATE_MIN_COUNT_USERS_ROOM,
    AWAITING_UPDATE_MAX_COUNT_USERS_ROOM,
    AWAITING_UPDATE_MIN_COST_GIFT_ROOM,
    AWAITING_START_RANDOMIZATION,
    AWAITING_USERNAME_DELETE,
    AWAITING_DELETE_CONFIRM,
    AWAITING_CONFIRM_LEAVE_ROOM
}
